name: "eulers-project"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Lint Euler's Project
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.3'
        otp-version: '25.1.2'
      working-directory: ./euler_project
    - name: Install dependencies
      run: mix deps.get
      working-directory: ./euler_project
    - name: Run Credo
      run: mix credo --strict
      working-directory: ./euler_project

  test:
    name: Test Euler's Project
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.3'
        otp-version: '25.1.2'
      working-directory: ./euler_project
    - name: Install dependencies
      run: mix deps.get
      working-directory: ./euler_project
    - name: Run tests
      run: mix test
      working-directory: ./euler_project
